# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'selling' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  inhibit_all_warnings!
  pod 'Alamofire', '4.8.0'
  pod 'AlamofireNetworkActivityLogger', '2.4.0'
  pod 'SwiftyJSON', '5.0.0'
  pod 'ObjectMapper', '3.4.2'
  pod 'SwiftyUserDefaults', '4.0.0'
  pod 'MBProgressHUD', '1.1.0'
  pod 'Localize-Swift', '2.0.0'
  pod 'ESPullToRefresh', '2.9'
  pod 'Kingfisher', '5.5.0'
  pod 'Spruce', '2.0.0'
  
  #Config pod
  post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
      config.build_settings.delete('CODE_SIGNING_ALLOWED')
      config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
        if ['Spruce'].include? target.name
          config.build_settings['SWIFT_VERSION'] = '4.0'
        end
      end
    end
  end
end
