# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'selling' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for selling

  target 'sellingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sellingUITests' do
    # Pods for testing
  end

end
